[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[global]
developmentMode = false
